
import java.awt.AlphaComposite;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.TexturePaint;
import java.awt.image.BufferedImage;
import java.awt.image.RenderedImage;
import java.awt.print.Book;
import java.awt.print.PageFormat;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;

/**
 * MSPAINT
 *
 * @author bns5273
 */
public class NewJFrame extends javax.swing.JFrame {

    private Color c1, c2, c3;
    private BasicStroke bs;
    private GradientPaint gp;
    private TexturePaint tp;
    private int oldx, oldy;
    private boolean filled;
    private float transparency;
    private Image background, foreground;
    private Shape s;

    /**
     * Creates new form NewJFrame
     *
     * @param g
     */
    public void paint(Graphics g) {
        super.paint(g);
        this.showEx();
        this.jPanel1.getGraphics().drawImage(this.background, 0, 0, null);
    }

    static void shape(NewJFrame my, Shape base) {
        my.s = base;
    }

    private void closeProg() {
        System.exit(0);
    }

    // this shows a line of the current settings in the bottom left
    public void showEx() {
        Graphics g = this.jPanel3.getGraphics();
        this.c1 = this.getColor();
        this.bs = this.getBs();
        this.transparency = this.transp();
        AlphaComposite ac = AlphaComposite.getInstance(3, this.transparency);
        Graphics2D g2d = (Graphics2D) g;
        g2d.setStroke(this.bs);
        g2d.setColor(this.c1);
        g2d.setComposite(ac);
        if (this.jToggleButton1.isSelected()) {
            g2d.setPaint(gp);
        }
        g2d.drawLine(0, 0, this.jPanel3.getWidth(), this.jPanel3.getHeight());
    }

    // opens a drawing file
    public void open() {
        JFileChooser choose = new JFileChooser(".");

        if (choose.showOpenDialog(null) == 0) {
            try {
                File nf = choose.getSelectedFile();
                this.background = ImageIO.read(nf);
                this.repaint();
            } catch (IOException ex) {
                System.out.println("There was an Error Loading the file");
            }
        }
    }

    // saves a drawing file
    public void save() {
        JFileChooser choose = new JFileChooser(".");
        if (choose.showOpenDialog(null) == 0) {
            try {
                File nf = choose.getSelectedFile();
                ImageIO.write((RenderedImage) ((Object) this.background), "png", nf);
            } catch (IOException ex) {
                System.out.println("There was an error saving the file");

            }
        }
    }

    // prints the drawing
    public void print() {
        PrinterJob print = PrinterJob.getPrinterJob();
        PageFormat page = print.pageDialog(new PageFormat());
        if (print.printDialog()) {
            Book bk = new Book();
            Printer p = new Printer(this.background);
            bk.append(p, page);
            print.setPageable(bk);
            try {
                print.print();
            } catch (PrinterException pe) {
            }

        }
    }

    // returns transparency value
    public float transp() {
        return 1.0f - (float) this.jSlider1.getValue() / 100.0f;
    }

    // returns color value
    public Color getColor() {
        return new Color(this.jSlider2.getValue(), this.jSlider3.getValue(), this.jSlider4.getValue());
    }

    // returns line thickness and dashed bool
    public BasicStroke getBs() {
        int lineWidth = this.jSlider5.getValue();

        float[] fa = new float[]{10.0f, 10.0f, 10.0f};
        if (this.jCheckBox1.isSelected()) {
            return new BasicStroke(lineWidth, 0, 2, 10.0f, fa, 10.0f);
        }
        return new BasicStroke(lineWidth);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saveButton1 = new SaveButton();
        try {
            closeButton1 = new CloseButton();
        } catch (java.io.IOException e1) {
            e1.printStackTrace();
        }
        jToolBar1 = new javax.swing.JToolBar();
        try {
            openButton2 = new OpenButton();
        } catch (java.io.IOException e1) {
            e1.printStackTrace();
        }
        saveButton2 = new SaveButton();
        clearButton1 = new ClearButton();
        printButton1 = new PrintButton();
        try {
            closeButton2 = new CloseButton();
        } catch (java.io.IOException e1) {
            e1.printStackTrace();
        }
        jToolBar2 = new javax.swing.JToolBar();
        ovalButton1 = new OvalButton();
        rectangleButton1 = new RectangleButton();
        lineButton1 = new LineButton();
        freeButton1 = new FreeButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jSlider5 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jCheckBox2 = new javax.swing.JCheckBox();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jSlider2 = new javax.swing.JSlider();
        jSlider3 = new javax.swing.JSlider();
        jSlider4 = new javax.swing.JSlider();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setRollover(true);

        openButton2.setFocusable(false);
        openButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        openButton2.setMaximumSize(new java.awt.Dimension(74, 74));
        openButton2.setMinimumSize(new java.awt.Dimension(25, 25));
        openButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        openButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(openButton2);

        saveButton2.setFocusable(false);
        saveButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saveButton2.setMaximumSize(new java.awt.Dimension(74, 74));
        saveButton2.setMinimumSize(new java.awt.Dimension(25, 25));
        saveButton2.setPreferredSize(new java.awt.Dimension(25, 25));
        saveButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        saveButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(saveButton2);

        clearButton1.setFocusable(false);
        clearButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        clearButton1.setMaximumSize(new java.awt.Dimension(74, 74));
        clearButton1.setMinimumSize(new java.awt.Dimension(25, 25));
        clearButton1.setPreferredSize(new java.awt.Dimension(25, 25));
        clearButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        clearButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(clearButton1);

        printButton1.setFocusable(false);
        printButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        printButton1.setMaximumSize(new java.awt.Dimension(74, 74));
        printButton1.setMinimumSize(new java.awt.Dimension(25, 25));
        printButton1.setPreferredSize(new java.awt.Dimension(25, 25));
        printButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        printButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(printButton1);

        closeButton2.setFocusable(false);
        closeButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        closeButton2.setMaximumSize(new java.awt.Dimension(74, 74));
        closeButton2.setMinimumSize(new java.awt.Dimension(25, 25));
        closeButton2.setPreferredSize(new java.awt.Dimension(25, 25));
        closeButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        closeButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(closeButton2);

        jToolBar2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar2.setRollover(true);

        ovalButton1.setFocusable(false);
        ovalButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ovalButton1.setMaximumSize(new java.awt.Dimension(43, 43));
        ovalButton1.setMinimumSize(new java.awt.Dimension(50, 25));
        ovalButton1.setPreferredSize(new java.awt.Dimension(50, 43));
        ovalButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ovalButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ovalButton1ActionPerformed(evt);
            }
        });
        jToolBar2.add(ovalButton1);

        rectangleButton1.setFocusable(false);
        rectangleButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rectangleButton1.setMaximumSize(new java.awt.Dimension(43, 43));
        rectangleButton1.setMinimumSize(new java.awt.Dimension(50, 25));
        rectangleButton1.setPreferredSize(new java.awt.Dimension(50, 43));
        rectangleButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rectangleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rectangleButton1ActionPerformed(evt);
            }
        });
        jToolBar2.add(rectangleButton1);

        lineButton1.setFocusable(false);
        lineButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lineButton1.setMaximumSize(new java.awt.Dimension(43, 43));
        lineButton1.setMinimumSize(new java.awt.Dimension(50, 25));
        lineButton1.setPreferredSize(new java.awt.Dimension(50, 25));
        lineButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lineButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lineButton1ActionPerformed(evt);
            }
        });
        jToolBar2.add(lineButton1);

        freeButton1.setFocusable(false);
        freeButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        freeButton1.setMaximumSize(new java.awt.Dimension(43, 43));
        freeButton1.setMinimumSize(new java.awt.Dimension(30, 25));
        freeButton1.setPreferredSize(new java.awt.Dimension(30, 25));
        freeButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        freeButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freeButton1ActionPerformed(evt);
            }
        });
        jToolBar2.add(freeButton1);

        jCheckBox1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox1.setText("Dashed");
        jCheckBox1.setFocusable(false);
        jCheckBox1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jCheckBox1.setMaximumSize(new java.awt.Dimension(60, 43));
        jCheckBox1.setMinimumSize(new java.awt.Dimension(60, 43));
        jCheckBox1.setPreferredSize(new java.awt.Dimension(60, 43));
        jCheckBox1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jCheckBox1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox1StateChanged(evt);
            }
        });
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jToolBar2.add(jCheckBox1);

        jCheckBox3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox3.setText("Filled");
        jCheckBox3.setFocusable(false);
        jCheckBox3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jCheckBox3.setMaximumSize(new java.awt.Dimension(60, 43));
        jCheckBox3.setMinimumSize(new java.awt.Dimension(60, 43));
        jCheckBox3.setPreferredSize(new java.awt.Dimension(60, 43));
        jCheckBox3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jToolBar2.add(jCheckBox3);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("Thickness:");
        jToolBar2.add(jLabel2);

        jSlider5.setMajorTickSpacing(20);
        jSlider5.setMinorTickSpacing(5);
        jSlider5.setValue(10);
        jSlider5.setMaximumSize(new java.awt.Dimension(100, 43));
        jSlider5.setMinimumSize(new java.awt.Dimension(100, 43));
        jSlider5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider5StateChanged(evt);
            }
        });
        jToolBar2.add(jSlider5);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setText("Transparency:");
        jLabel1.setMaximumSize(new java.awt.Dimension(100, 43));
        jLabel1.setMinimumSize(new java.awt.Dimension(100, 25));
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 25));
        jToolBar2.add(jLabel1);

        jSlider1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jSlider1.setPaintLabels(true);
        jSlider1.setValue(0);
        jSlider1.setMaximumSize(new java.awt.Dimension(100, 43));
        jSlider1.setMinimumSize(new java.awt.Dimension(100, 43));
        jSlider1.setPreferredSize(new java.awt.Dimension(100, 43));
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        jToolBar2.add(jSlider1);

        jCheckBox2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBox2.setSelected(true);
        jCheckBox2.setText("Cyclic");
        jCheckBox2.setFocusable(false);
        jCheckBox2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jCheckBox2.setMaximumSize(new java.awt.Dimension(47, 43));
        jCheckBox2.setMinimumSize(new java.awt.Dimension(47, 43));
        jCheckBox2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jToolBar2.add(jCheckBox2);

        jToggleButton1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jToggleButton1.setText("Gradiant");
        jToggleButton1.setFocusable(false);
        jToggleButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton1.setMaximumSize(new java.awt.Dimension(100, 43));
        jToggleButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jToolBar2.add(jToggleButton1);

        jToggleButton2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jToggleButton2.setText("Texture");
        jToggleButton2.setFocusable(false);
        jToggleButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton2.setMaximumSize(new java.awt.Dimension(100, 43));
        jToggleButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jToolBar2.add(jToggleButton2);

        jToggleButton3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jToggleButton3.setText("Text:");
        jToggleButton3.setFocusable(false);
        jToggleButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton3.setMaximumSize(new java.awt.Dimension(100, 43));
        jToggleButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        jToolBar2.add(jToggleButton3);

        jTextField1.setAlignmentY(0.2F);
        jTextField1.setMaximumSize(new java.awt.Dimension(75, 25));
        jTextField1.setMinimumSize(new java.awt.Dimension(75, 25));
        jTextField1.setPreferredSize(new java.awt.Dimension(75, 25));
        jToolBar2.add(jTextField1);

        jPanel1.setMaximumSize(new java.awt.Dimension(400, 400));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel1MouseReleased(evt);
            }
        });
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 51));
        jPanel2.setFocusable(false);
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jPanel3.setMaximumSize(new java.awt.Dimension(50, 25));
        jPanel3.setMinimumSize(new java.awt.Dimension(50, 25));
        jPanel3.setPreferredSize(new java.awt.Dimension(50, 25));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3);

        jSlider2.setBackground(new java.awt.Color(255, 255, 255));
        jSlider2.setForeground(new java.awt.Color(255, 0, 0));
        jSlider2.setMajorTickSpacing(50);
        jSlider2.setMaximum(255);
        jSlider2.setMinorTickSpacing(10);
        jSlider2.setPaintLabels(true);
        jSlider2.setPaintTicks(true);
        jSlider2.setValue(0);
        jSlider2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jSlider2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider2StateChanged(evt);
            }
        });
        jPanel2.add(jSlider2);

        jSlider3.setBackground(new java.awt.Color(255, 255, 255));
        jSlider3.setForeground(new java.awt.Color(51, 255, 51));
        jSlider3.setMajorTickSpacing(50);
        jSlider3.setMaximum(255);
        jSlider3.setMinorTickSpacing(10);
        jSlider3.setPaintLabels(true);
        jSlider3.setPaintTicks(true);
        jSlider3.setValue(0);
        jSlider3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider3StateChanged(evt);
            }
        });
        jPanel2.add(jSlider3);

        jSlider4.setBackground(new java.awt.Color(255, 255, 255));
        jSlider4.setForeground(new java.awt.Color(0, 0, 255));
        jSlider4.setMajorTickSpacing(50);
        jSlider4.setMaximum(255);
        jSlider4.setMinorTickSpacing(10);
        jSlider4.setPaintLabels(true);
        jSlider4.setPaintTicks(true);
        jSlider4.setValue(0);
        jSlider4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider4StateChanged(evt);
            }
        });
        jPanel2.add(jSlider4);

        jMenu1.setText("File");

        jMenuItem1.setText("Open");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Save");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem4.setText("Clear");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Print");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem3.setText("Exit");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // save
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.save();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    // close from menu
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.closeProg();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    // close
    private void closeButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButton2ActionPerformed
        this.closeProg();
    }//GEN-LAST:event_closeButton2ActionPerformed

    // print from menu
    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        this.print();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    // sets tool to free draw
    private void freeButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freeButton1ActionPerformed
        shape(NewJFrame.this, new Free());
    }//GEN-LAST:event_freeButton1ActionPerformed

    // red
    private void jSlider2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider2StateChanged
        this.repaint();
    }//GEN-LAST:event_jSlider2StateChanged

    // green
    private void jSlider3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider3StateChanged
        this.repaint();
    }//GEN-LAST:event_jSlider3StateChanged

    // blue
    private void jSlider4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider4StateChanged
        this.repaint();
    }//GEN-LAST:event_jSlider4StateChanged

    // thickness
    private void jSlider5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider5StateChanged
        this.repaint();
    }//GEN-LAST:event_jSlider5StateChanged

    private void jCheckBox1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox1StateChanged
    }//GEN-LAST:event_jCheckBox1StateChanged

    // dashed?
    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        this.repaint();
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    // transparency
    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        this.repaint();
    }//GEN-LAST:event_jSlider1StateChanged

    // gradiant
    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        if (jToggleButton1.isSelected()) {
            if (jCheckBox2.isSelected()) {
                this.c2 = null;
                this.c2 = JColorChooser.showDialog(rootPane, "Choose first color", c2);
                this.c3 = null;
                this.c3 = JColorChooser.showDialog(rootPane, "Choose second 2", c3);
                this.gp = new GradientPaint(this.jPanel1.getWidth() / 2, 0.0f, this.c2, this.jPanel1.getWidth() / 2, this.jPanel1.getHeight(), this.c3);
            } else {
                this.c2 = null;
                c2 = JColorChooser.showDialog(rootPane, "Choose first color", c2);
                this.c3 = null;
                this.c3 = JColorChooser.showDialog(rootPane, "Choose second 2", c3);
                this.gp = new GradientPaint(this.jPanel1.getWidth() / 2, 0.0f, this.c3, this.jPanel1.getWidth() / 2, this.jPanel1.getHeight(), this.c2);
            }
            this.repaint();
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    // filled
    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        this.filled = jCheckBox3.isSelected();
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    // get starting coordinates
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        oldx = evt.getX();
        oldy = evt.getY();

        if (this.background == null) {
            this.background = this.createImage(this.jPanel1.getWidth(), this.jPanel1.getHeight());
            this.foreground = this.createImage(this.jPanel1.getWidth(), this.jPanel1.getHeight());
        }
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseReleased
        Graphics backg = this.background.getGraphics();
        Graphics foreg = this.foreground.getGraphics();
        foreg.setColor(this.c1);

        // for text drawing
        if (this.jToggleButton3.isSelected()) {
            foreg.drawString(this.jTextField1.getText(), evt.getX(), evt.getY());
        }
        backg.drawImage(this.foreground, 0, 0, null);
        NewJFrame.this.repaint();
    }//GEN-LAST:event_jPanel1MouseReleased

    // texture
    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        if (jToggleButton2.isSelected()) {
            JFileChooser choose = new JFileChooser(".");
            if (choose.showOpenDialog(null) == 0) {
                ImageIcon ii = new ImageIcon(choose.getSelectedFile().getAbsolutePath());
                Image i = ii.getImage();
                BufferedImage text = new BufferedImage(128, 128, 6);
                Graphics2D bT = text.createGraphics();
                bT.drawImage(i, 0, 0, null);
                Rectangle r = new Rectangle(128, 128);
                this.tp = new TexturePaint(text, r);
            }
        }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    // for live updates
    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int width = Math.abs(evt.getX() - this.oldx);
        int height = Math.abs(evt.getY() - this.oldy);
        int x = this.oldx < evt.getX() ? this.oldx : evt.getX();
        int y = this.oldy < evt.getY() ? this.oldy : evt.getY();
        if (this.s instanceof Line || this.s instanceof Free) {
            width = evt.getX();
            height = evt.getY();
            x = this.oldx;
            y = this.oldy;
        }

        Graphics foreg = this.foreground.getGraphics();
        foreg.drawImage(this.background, 0, 0, null);

        if (!this.jToggleButton3.isSelected()) {
            if (this.jToggleButton1.isSelected() && !this.jToggleButton2.isSelected()) {
                this.s.drawS(foreg, x, y, width, height, this.c1, this.bs, this.filled, this.transparency, this.gp, null);
            } else if (!this.jToggleButton1.isSelected() && this.jToggleButton2.isSelected()) {
                this.s.drawS(foreg, x, y, width, height, this.c1, this.bs, this.filled, this.transparency, null, this.tp);
            } else if (this.jToggleButton1.isSelected() && this.jToggleButton2.isSelected()) {
                this.s.drawS(foreg, x, y, width, height, this.c1, this.bs, this.filled, this.transparency, this.gp, this.tp);
            } else {
                this.s.drawS(foreg, x, y, width, height, this.c1, this.bs, this.filled, this.transparency, null, null);
            }
        }
        this.jPanel1.getGraphics().drawImage(this.foreground, 0, 0, null);
        if (this.s instanceof Free) {
            oldx = width;
            oldy = height;
            Graphics backg = this.background.getGraphics();
            backg.drawImage(this.foreground, 0, 0, null);
        }
    }//GEN-LAST:event_jPanel1MouseDragged

    // oval
    private void ovalButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ovalButton1ActionPerformed
        shape(NewJFrame.this, new Oval());
    }//GEN-LAST:event_ovalButton1ActionPerformed

    // rect
    private void rectangleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rectangleButton1ActionPerformed
        shape(NewJFrame.this, new Rect());
    }//GEN-LAST:event_rectangleButton1ActionPerformed

    // clear from menu
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        this.background = null;
        this.repaint();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    // clear
    private void clearButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButton1ActionPerformed
        this.background = null;
        this.repaint();
    }//GEN-LAST:event_clearButton1ActionPerformed

    // line
    private void lineButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineButton1ActionPerformed
        shape(NewJFrame.this, new Line());
    }//GEN-LAST:event_lineButton1ActionPerformed

    // open
    private void openButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openButton2ActionPerformed
        this.open();
    }//GEN-LAST:event_openButton2ActionPerformed

    // open from menu
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.open();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    // save
    private void saveButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButton2ActionPerformed
        this.save();
    }//GEN-LAST:event_saveButton2ActionPerformed

    // print
    private void printButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButton1ActionPerformed
        this.print();
    }//GEN-LAST:event_printButton1ActionPerformed

    // cyclic?
    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        if (jCheckBox2.isSelected()) {
            this.gp = new GradientPaint(this.jPanel1.getWidth() / 2, 0.0f, this.c2, this.jPanel1.getWidth() / 2, this.jPanel1.getHeight(), this.c3);
        } else {
            this.gp = new GradientPaint(this.jPanel1.getWidth() / 2, 0.0f, this.c3, this.jPanel1.getWidth() / 2, this.jPanel1.getHeight(), this.c2);
        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            NewJFrame njf = new NewJFrame();
            njf.setDefaultCloseOperation(3);
            njf.setVisible(true);
        });

    }

    public NewJFrame() {
        initComponents();
        this.s = new Oval();
        this.filled = false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ClearButton clearButton1;
    private CloseButton closeButton1;
    private CloseButton closeButton2;
    private FreeButton freeButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JSlider jSlider3;
    private javax.swing.JSlider jSlider4;
    private javax.swing.JSlider jSlider5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private LineButton lineButton1;
    private OpenButton openButton2;
    private OvalButton ovalButton1;
    private PrintButton printButton1;
    private RectangleButton rectangleButton1;
    private SaveButton saveButton1;
    private SaveButton saveButton2;
    // End of variables declaration//GEN-END:variables
}
